.codecov.yml, .gitignore, .travis.yml, README.md, appveyor.yml, src/LinQuadOptInterface.jl, src/mockoptimizer.jl, src/solver_interface.jl, test/runtests.jl
This will enable testing  LQOI without solvers.
Currently only testing linear problems
=> Add Mock Solver

REQUIRE, src/constraints/scalaraffine.jl, src/constraints/scalarquadratic.jl, src/constraints/vectoraffine.jl, src/objective.jl
Updates after the big change (ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/351).
=> Updates for MOI v0.3

src/constraints/scalaraffine.jl, src/constraints/vectoraffine.jl, src/mockoptimizer.jl, src/objective.jl, src/solver_interface.jl
=> Add specialized versions of change_coefficient

src/LinQuadOptInterface.jl
Closes #18 
Tests for this bug covered by https://github.com/JuliaOpt/MathOptInterface.jl/pull/379
=> Fix deleting vectoraffine constraints

src/constraints/scalaraffine.jl, src/constraints/scalarquadratic.jl, src/objective.jl, src/solver_interface.jl
related to #8
Should resolve:
- get ConstraintSet of a ScalarAffineFunction-inInterval constraint.
- get ConstraintSet of a ScalarQuadraticFunction constraint.
- get ConstraintFunction of a ScalarQuadraticFunction constraint. 
- get quadratic function
@odow
=> Add quadratics and interval features

src/constraints/singlevariable.jl, test/runtests.jl
This is a temporary replacement for #30 
Keeps constraint ordering good.
I think we should go for #30 though...
=> Alternative protection for weird bound combination (temp replace for #30)

.travis.yml, REQUIRE, appveyor.yml, src/LinQuadOptInterface.jl, src/constraints/scalaraffine.jl, src/constraints/scalarquadratic.jl, src/constraints/vectoraffine.jl, src/constraints/vectorofvariables.jl, src/mockoptimizer.jl, src/solve.jl, src/solver_interface.jl, src/variables.jl, test/runtests.jl
Package was broken in 0.7.
With this, it passes tests without deprecation warnings on both 0.6 and 0.7.
=> Fixes for latest julia 0.7

src/constraints/scalaraffine.jl, src/constraints/vectoraffine.jl
=> fix handling of empty rows in vector affine functions

src/constraints/scalaraffine.jl, test/runtests.jl
=> Fix handling of constraint constants

src/solve.jl, src/solver_interface.jl
=> add functionality for dual farkas on variables bound

.travis.yml, appveyor.yml, src/LinQuadOptInterface.jl, src/constraints.jl, src/constraints/scalaraffine.jl, src/mockoptimizer.jl, src/solver_interface.jl, src/variables.jl, test/contconic.jl, test/contlinear.jl, test/contquadratic.jl, test/intlinear.jl
Supersedes #60 since it was just easier to do the rebase myself.
Closes #60
=> Updates for Julia v1

REQUIRE, src/LinQuadOptInterface.jl, src/constraints.jl, src/constraints/scalaraffine.jl, src/constraints/scalarquadratic.jl, src/constraints/singlevariable.jl, src/constraints/vectoraffine.jl, src/constraints/vectorofvariables.jl, src/copy.jl, src/objective.jl, src/solve.jl, src/variables.jl, test/contconic.jl, test/runtests.jl
Tested with LQOI and with GLPK. Closes #63
=> Updates for MOI 0.6

src/constraints/singlevariable.jl
This, in conjunction with (GLPK Bug I will link to) caused a crash when changing the value of a fixed variable.
We end up in the situation where if x==value, then changing value as first the lower, then the upper (or vice-versa) can end up in the situation where upper < lower.
=> Merge calls to change_variable_bounds!

src/objective.jl, test/runtests.jl
Closes https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/67
=> Implements ObjectiveFunctionType

src/LinQuadOptInterface.jl, src/constraints.jl, src/variables.jl, test/runtests.jl
Closes #71.
This PR needs a new tag of MOI to pass tests on travis, but is passing locally with the latest MOI master.
=> Allow setting of duplicate variable and constraint names

REQUIRE, test/runtests.jl
See https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/72#issuecomment-439069238
=> Reenable name tests

src/solver_interface.jl, src/variables.jl, test/runtests.jl
=> Throw UnsupportedAttribute when mip starts not supported.

src/LinQuadOptInterface.jl, src/mockoptimizer.jl, test/runtests.jl
=> Implement model printing

src/solve.jl
Following discussion in https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/86
=> Remove dual sense assertion

src/LinQuadOptInterface.jl, test/runtests.jl
=> Add names to AttributesSet

src/constraints/singlevariable.jl, test/runtests.jl
See the discussion in https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/89
Closes #89.
=> Relax restriction on adding binary constraints

src/LinQuadOptInterface.jl, src/constraints.jl, src/variables.jl, test/runtests.jl
=> Implement lazy reverse name lookup

.travis.yml, REQUIRE, appveyor.yml, src/LinQuadOptInterface.jl, src/constraints/scalaraffine.jl, src/constraints/scalarquadratic.jl, src/constraints/vectoraffine.jl, src/mockoptimizer.jl, src/objective.jl, src/solver_interface.jl, test/runtests.jl
This is a cleaned up pull request from canceled PR #99
=> Remove support for pre Julia v1.0
